---
title: "Ridgeline Graph"
author: "Eugenio Paglino"
date: \today
output: pdf_document
---

```{r, echo=F, message=F,warning=F}
# Loading necessary packages

library(USAboundaries)
library(sf)
library(lubridate)
library(here)
library(scico)
library(ggthemes)
library(glue)
library(ggnewscale)
library(ggh4x)
library(tidyverse)
```

```{r}
rm(list=ls())

i_am('secondYearPaper/R/relativeExcessGraphs.Rmd')

inDir <- here('data','input')
outDir <- here('secondYearPaper','data','output')
figuresDir <- here('secondYearPaper','figuresBayes')
tablesDir <- here('secondYearPaper','tables')
```

```{r}
load(here('secondYearPaper','R','RObjects','simulationsDF.RData'))
```

```{r}
plotDataStates <- simulationsDF %>%
  filter(!(riskLevel == 'total' & method == 'single')) %>%
  group_by(state,census_division,year,riskLevel,type) %>%
  summarize(across(V1:V1000, ~ sum(.x,na.rm=T)),
            individuals = sum(individuals,na.rm=T)) %>%
  ungroup() %>%
  pivot_longer(V1:V1000,names_to = 'simNum', values_to = 'expMig') %>%
  mutate(excMig = individuals-expMig) %>%
  group_by(state,census_division,year,riskLevel,type) %>%
  summarize(individuals = mean(individuals),
            expMigLow = quantile(expMig,probs=c(0.1)),
            expMigMed = quantile(expMig,probs=c(0.5)),
            expMigUp = quantile(expMig,probs=c(0.9)),
            excMigLow = quantile(excMig,probs=c(0.1)),
            excMigMed = quantile(excMig,probs=c(0.5)),
            excMigUp = quantile(excMig,probs=c(0.9)),
            relExcLow = quantile(excMig/expMig,probs=c(0.1)),
            relExcMed = quantile(excMig/expMig,probs=c(0.5)),
            relExcUp = quantile(excMig/expMig,probs=c(0.9))) %>%
  ungroup()
```

```{r}
hurricaneData <- simulationsDF %>%
  filter(!(riskLevel == 'total' & method == 'single')) %>%
  select(FIPSCode,state,census_division,year,censored) %>%
  group_by(state,year) %>%
  summarise(anyHurricane = sum(censored)>0) %>%
  ungroup()

hurricaneData <- plotDataStates %>%
  filter(riskLevel != 'total') %>%
  group_by(state) %>%
  summarise(maxValRel = max(relExcUp),
            maxValAbs = max(excMigUp),
            minValRel = min(relExcLow),
            minValAbs = min(excMigLow)) %>%
  ungroup() %>%
  right_join(hurricaneData,by='state')
```

```{r,fig.height=6,fig.width=5}
dotGraphRel <- plotDataStates %>%
  filter(riskLevel != 'total',
         year>=2005) %>%
  mutate(typeLong = if_else(type=='In','In-Migration','Out-Migration')) %>%
  ggplot() +
  geom_hline(yintercept = 0,linetype='dotted') + 
  geom_rect(data=filter(hurricaneData,year>=2005),
            mapping=aes(xmin=year-0.35,xmax=year+0.35,
                        ymin=minValRel,ymax=maxValRel,alpha=anyHurricane)) + 
  geom_errorbar(mapping=aes(x=year,ymin=-0.3,ymax=0.3),
                position=position_dodge(width = 0.8),width = 0,alpha=0) +
  geom_errorbar(mapping=aes(x=year,ymin=relExcLow,ymax=relExcUp,group=riskLevel),
                position=position_dodge(width = 0.8),width = 0.2) +
  geom_point(mapping=aes(x=year,y=relExcMed,fill=relExcLow>0 | relExcUp<0,
                         group=riskLevel,shape=riskLevel),
             size=2,
             position=position_dodge(width = 0.8)) +
  facet_grid(state~typeLong,space="free_y",scales="free_y",switch='y') +
  scale_y_continuous(breaks=c(-0.5,0,0.5,1,1.5,2,3,5)) +
  scale_x_continuous(breaks=2005:2010,expand = expansion(add = 0.1)) +
  scale_shape_manual(values = c(21:25),
                     breaks = c('risk1','risk2','risk3','risk4','risk5'),
                     labels = c('1st','2nd','3rd','4th','5th'),
                     name = 'Quintile of Per Capita Damage\nfrom Natural Disasters (Risk Level)') +
  scale_fill_manual(values=c('white','red'),
                    breaks=c(F,T),
                    labels=c('No','Yes'),
                    name='Posterior Probability that \nExcess > 0 or that Excess <0 is > 90%') +
  scale_alpha_manual(values=c(0,0.2),
                     breaks=c(F,T),
                     labels=c('No','Yes'),
                     name='Hit by Tropical Storm?') + 
  labs(x='',
       y='Relative Excess') +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        strip.text.y.left = element_text(angle=0),
        strip.text.x = element_text(size=14),
        strip.placement = "outside",
        legend.position = 'bottom',
        legend.direction = 'vertical',
        legend.title = element_text(size=9),
        legend.margin = margin(t=-10),
        axis.text.x = element_text(angle=45,vjust=0.2)) +
  guides(shape = guide_legend(nrow=2,byrow=T),
         fill = guide_legend(nrow=1,override.aes=aes(shape=21)),
         alpha = guide_legend(nrow=1,override.aes=aes(color='black',size=0.1)))

dotGraphRel
```

```{r}
pdf(here(figuresDir,'dotGraphRel.pdf'), width = 10, height = 14)
dotGraphRel
dev.off()
```

```{r}
plotDataPeriods <- simulationsDF %>%
  filter(!(riskLevel == 'total' & method == 'single')) %>%
  filter(riskLevel=='total') %>%
  mutate(period = factor(if_else(year<2010,floor((year-1990)/5) + 1,4),
                         levels=1:4,
                         labels=map(1:4,function(x) 
                           glue('{1990+(x-1)*5}-{1990+(x-1)*5+4}')))) %>%
  group_by(FIPSCode,state,census_division,period,type) %>%
  summarize(across(V1:V1000, ~ sum(.x,na.rm=T)),
            individuals = sum(individuals,na.rm=T),
            pop = sum(pop)) %>%
  ungroup() %>%
  pivot_longer(V1:V1000,names_to = 'simNum', values_to = 'expMig') %>%
  mutate(excMig = individuals-expMig) %>%
  group_by(FIPSCode,state,census_division,period,type) %>%
  summarize(individuals = mean(individuals),
            expMigLow = quantile(expMig,probs=c(0.05)),
            expMigMed = quantile(expMig,probs=c(0.5)),
            expMigUp = quantile(expMig,probs=c(0.95)),
            excMigLow = quantile(excMig,probs=c(0.05)),
            excMigMed = quantile(excMig,probs=c(0.5)),
            excMigUp = quantile(excMig,probs=c(0.95)),
            relExcLow = quantile(excMig/expMig,probs=c(0.05)),
            relExcMed = quantile(excMig/expMig,probs=c(0.5)),
            relExcUp = quantile(excMig/expMig,probs=c(0.95)),
            probPositive = sum(excMig>0)/n(),
            probNegative = sum(excMig<0)/n(),
            pop=mean(pop)) %>%
  ungroup()
```

```{r}
fillBreaksPos <- quantile(pull(filter(plotDataPeriods,relExcMed>=0),relExcMed),
                          seq(0,1,0.10),na.rm=T)
fillBreaksNeg <- quantile(pull(filter(plotDataPeriods,relExcMed<=0),relExcMed),
                          seq(0,1,0.25),na.rm=T)

fillBreaks <- c(fillBreaksNeg,fillBreaksPos[-1])
names(fillBreaks) <- NULL
```

```{r}
manualBreaksExc <- c(fillBreaks[1],
                  -0.1,-0.025,0.05,0.15,1,
                  fillBreaks[length(fillBreaks)])
manualPaletteExc <- scico(9, palette = 'vikO')[3:8]

manualBreaksProb <- c(0.5,0.75,0.8,0.85,0.9,0.95,1)
```

```{r}
plotDataPeriods <- plotDataPeriods %>%
  rowwise() %>%
  mutate(maxProbNonZero = max(probPositive,probNegative)) %>%
  select(FIPSCode,state,census_division,period,type,
         relExcMed,maxProbNonZero) %>%
  mutate(variable='relExcMed') %>%
  ungroup()

plotDataPeriods <- plotDataPeriods %>%
  mutate(variable='maxProbNonZero') %>%
  add_row(plotDataPeriods)

plotDataPeriods <- plotDataPeriods %>%
  mutate(relExcMed = if_else(variable=='relExcMed',relExcMed,NA_real_),
         maxProbNonZero = if_else(variable=='maxProbNonZero',maxProbNonZero,NA_real_),
         variable = factor(variable,
                           levels=c('relExcMed','maxProbNonZero'),
                           labels=c('Relative Excess','Max[P(Excess > 0),P(Excess<0)]')))
```

```{r}
counties <- us_counties()
# Transform to Albers for making map of US
counties <- st_transform(counties, 5070)

counties <- counties %>%
  select(geoid,stusps,geometry) %>%
  filter(stusps != 'PR') %>%
  select(-stusps) %>%
  rename(FIPSCode = geoid) 
```

```{r}
plotDataPeriods <- counties %>%
  right_join(plotDataPeriods,by='FIPSCode')
```

```{r, fig.height=5,fig.width=5}
excessMaps <- plotDataPeriods %>%
  mutate(typeLong = if_else(type=='In','In-Migration','Out-Migration')) %>%
  ggplot() + 
  geom_sf(mapping=aes(fill = cut(relExcMed,manualBreaksExc)),
          color=NA) +
  scale_fill_manual(name='Relative Excess',values=manualPaletteExc,na.translate = F) +
  new_scale_fill() +
  geom_sf(mapping=aes(fill = cut(maxProbNonZero,manualBreaksProb)),
          color=NA) +
  scale_fill_manual(name='Max[P(Excess > 0),P(Excess<0)]',
                    values=scico(7, palette = 'oslo',direction = -1)[-1],
                    na.value = 'transparent',na.translate = F) +
  facet_nested(period ~ typeLong + variable) +
  theme_map() +
  theme(legend.position = 'bottom')

excessMaps
```

```{r}
pdf(here(figuresDir,'excessMaps.pdf'), width = 10, height = 10)
excessMaps
dev.off()
```

```{r}
countyData <- simulationsDF %>%
  filter(riskLevel=='total') %>%
  filter(countyID %in% c('Charlotte 12015','Stone 28131',
                         'Fayette 48149','St Tammany 22103',
                         'Acadia 22001','Cameron 22023')) %>%
  group_by(FIPSCode,countyID,state,census_division,year,type,method) %>%
  summarize(across(V1:V1000, ~ sum(.x,na.rm=T)),
            individuals = sum(individuals,na.rm=T),
            pop = sum(pop),
            censored = min(censored)) %>%
  ungroup() %>%
  pivot_longer(V1:V1000,names_to = 'simNum', values_to = 'expMig') %>%
  mutate(excMig = individuals-expMig) %>%
  group_by(FIPSCode,countyID,state,census_division,year,type,method) %>%
  summarize(individuals = mean(individuals),
            expMigLow = quantile(expMig,probs=c(0.05)),
            expMigMed = quantile(expMig,probs=c(0.5)),
            expMigUp = quantile(expMig,probs=c(0.95)),
            excMigLow = quantile(excMig,probs=c(0.05)),
            excMigMed = quantile(excMig,probs=c(0.5)),
            excMigUp = quantile(excMig,probs=c(0.95)),
            relExcLow = quantile(excMig/expMig,probs=c(0.05)),
            relExcMed = quantile(excMig/expMig,probs=c(0.5)),
            relExcUp = quantile(excMig/expMig,probs=c(0.95)),
            probPositive = sum(excMig>0)/n(),
            probNegative = sum(excMig<0)/n(),
            pop=mean(pop),
            censored = min(censored)) %>%
  ungroup()
```

```{r}
modelExamples <- countyData %>%
  mutate(
    censored = factor(
      case_when(
        censored == 1 ~ 'Affected by a Storm',
        TRUE ~ 'Not Affected by a Storm'
        ),
      levels=c('Not Affected by a Storm','Affected by a Storm')
      ),
    countyID = factor(countyID,
                      levels=c('Fayette 48149','Charlotte 12015',
                               'Stone 28131','St Tammany 22103',
                               'Acadia 22001','Cameron 22023')),
    method = if_else(method=='single','Separate Total Model','Total from Risk-Specific Models'),
    type = if_else(type=='In','In-Migration','Out-Migration')
    ) %>%
  ggplot() +
  geom_point(mapping=aes(x=year,y=(individuals/pop)*1000,shape=censored)) +
  geom_line(mapping=aes(x=year,y=(expMigMed/pop)*1000,color='Expected Rate with 80% PI')) +
  geom_ribbon(mapping=aes(x=year,ymin=(expMigLow/pop)*1000,ymax=(expMigUp/pop)*1000,fill='Expected Rate with 80% PI'),
              alpha=0.3) +
  labs(x='',
       y='Migration Rate (every 1,000 residents)',
       color='',
       fill='',
       shape='Observed Rate') +
  facet_nested(countyID~type+method) +
  theme_bw() +
  theme(legend.position = 'bottom',
        strip.text.y = element_text(angle=0))

modelExamples
```

```{r}
pdf(here(figuresDir,'modelExamples.pdf'), width = 10, height = 10)
modelExamples
dev.off()
```
